#!/bin/bash
set -e
mkdir -p ./tmp
#echo "---> Testing gx_pagesize (in gx.h)"
#gcc -O2 -Wall -I ../ test/test_pagesize.c -o tmp/tst && tmp/tst
#echo ""
#echo ""
#echo "---> Testing some memorymapping stuff"
#dd if=/dev/urandom of=tmp/testrand.txt bs=4096 count=10
#gcc -O2 -I ../ test/test_mmap.c -o tmp/tst && tmp/tst
#echo ""
#echo ""
#echo "---> Testing futexes (in gx_mfd.h)"
#gcc -O2 -Wall -I ../ test/test_futex.c -o tmp/tst && tmp/tst
#echo ""
#echo ""
#echo "---> Testing gx_clone (in gx.h)"
#gcc -O2 -Wall -g -O0 -I ../ test/test_clone.c -o tmp/tst && tmp/tst
#echo ""
#echo ""
#echo "---> Testing gx_mfd"
#gcc -O2 -Wall -I ../ test/test_gx_mfd.c -o tmp/tst && tmp/tst
#echo ""
#echo ""
#echo "---> Testing sha2"
#gcc -O2 -Wall -g -O0 -I ../ test/test_sha2.c -o tmp/tst && tmp/tst
#echo ""
#echo ""
#echo "---> Testing gx_token"
#gcc -O2 -Wall -g -O0 -I ../ test/test_gx_token.c -o tmp/tst && tmp/tst
echo ""
echo ""
echo "---> Testing gx_error (logging + error handling)"
gcc -O2 -Wall -g -O0 -I ../ test/test_gx_error.c -o tmp/tst && tmp/tst
echo ""
echo ""
echo "Done. Apparently passed."
rm -rf ./tmp
