#!/bin/bash
set -e
mkdir -p ./tmp
echo "Testing gx_mfd"
#gcc -I ../ test/test_gx_mfd.c -o tmp/tst && tmp/tst
echo "  skip"
echo "Testing gx_pagesize (in gx.h)"
gcc -I ../ test/test_pagesize.c -o tmp/tst && tmp/tst
#gcc -I ../ test/test_mmap.c -o tmp/tst && tmp/tst
rm -rf ./tmp
